// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	grpc "google.golang.org/grpc"
)

// ILoggingInterceptor is an autogenerated mock type for the ILoggingInterceptor type
type ILoggingInterceptor struct {
	mock.Mock
}

// StreamServerInterceptor provides a mock function with no fields
func (_m *ILoggingInterceptor) StreamServerInterceptor() grpc.StreamServerInterceptor {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StreamServerInterceptor")
	}

	var r0 grpc.StreamServerInterceptor
	if rf, ok := ret.Get(0).(func() grpc.StreamServerInterceptor); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(grpc.StreamServerInterceptor)
		}
	}

	return r0
}

// UnaryServerInterceptor provides a mock function with no fields
func (_m *ILoggingInterceptor) UnaryServerInterceptor() grpc.UnaryServerInterceptor {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for UnaryServerInterceptor")
	}

	var r0 grpc.UnaryServerInterceptor
	if rf, ok := ret.Get(0).(func() grpc.UnaryServerInterceptor); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(grpc.UnaryServerInterceptor)
		}
	}

	return r0
}

// NewILoggingInterceptor creates a new instance of ILoggingInterceptor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewILoggingInterceptor(t interface {
	mock.TestingT
	Cleanup(func())
}) *ILoggingInterceptor {
	mock := &ILoggingInterceptor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
