// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	grpc "google.golang.org/grpc"
)

// IStreamInterceptor is an autogenerated mock type for the IStreamInterceptor type
type IStreamInterceptor struct {
	mock.Mock
}

// StreamServerInterceptor provides a mock function with no fields
func (_m *IStreamInterceptor) StreamServerInterceptor() grpc.StreamServerInterceptor {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StreamServerInterceptor")
	}

	var r0 grpc.StreamServerInterceptor
	if rf, ok := ret.Get(0).(func() grpc.StreamServerInterceptor); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(grpc.StreamServerInterceptor)
		}
	}

	return r0
}

// NewIStreamInterceptor creates a new instance of IStreamInterceptor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIStreamInterceptor(t interface {
	mock.TestingT
	Cleanup(func())
}) *IStreamInterceptor {
	mock := &IStreamInterceptor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
