// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// IInterceptorManager is an autogenerated mock type for the IInterceptorManager type
type IInterceptorManager struct {
	mock.Mock
}

// GetStreamInterceptors provides a mock function with no fields
func (_m *IInterceptorManager) GetStreamInterceptors() []grpc.StreamServerInterceptor {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStreamInterceptors")
	}

	var r0 []grpc.StreamServerInterceptor
	if rf, ok := ret.Get(0).(func() []grpc.StreamServerInterceptor); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]grpc.StreamServerInterceptor)
		}
	}

	return r0
}

// GetUnaryInterceptors provides a mock function with no fields
func (_m *IInterceptorManager) GetUnaryInterceptors() []grpc.UnaryServerInterceptor {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUnaryInterceptors")
	}

	var r0 []grpc.UnaryServerInterceptor
	if rf, ok := ret.Get(0).(func() []grpc.UnaryServerInterceptor); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]grpc.UnaryServerInterceptor)
		}
	}

	return r0
}

// NewIInterceptorManager creates a new instance of IInterceptorManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIInterceptorManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *IInterceptorManager {
	mock := &IInterceptorManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
